import { LevelDefinition, StarThresholds } from './level';

/**
 * The hand-authored levels, in play order. Levels 1-20 are World 1
 * (Gravity); levels 21-30 are World 2 (Anchors) - see `src/game/worlds`.
 *
 * This is the canonical example of the data-driven level format: nothing
 * here is generated or computed - it is plain, serializable data using
 * only mechanics that exist in the engine (gravity, static obstacles,
 * multiple objects, targets, and - from level 21 - anchored objects). The
 * same shape (`LevelDefinition`) is meant to scale to thousands of levels
 * later, whether hand-authored or produced by a procedural generator (not
 * built yet).
 *
 * Progression:
 *  - 1-5:   very easy - teaches the basic mechanic (all four directions,
 *           and combining two directions), zero obstacles.
 *  - 6-10:  introduces obstacles and positioning - using an obstacle as a
 *           stop, a wall, or an alignment tool before dropping.
 *  - 11-15: multiple objects and more complex sequences - objects that
 *           block/stack on each other, combined with obstacles.
 *  - 16-20: requires planning several gravity changes ahead - detours,
 *           "move this piece out of the way first", ending on the hardest
 *           puzzle in World 1.
 *  - 21-23: teach ANCHORED OBJECTS - a piece gravity never moves, which
 *           every normal object collides with like a wall.
 *  - 24-26: combine anchors with obstacles (two kinds of fixed blocker).
 *  - 27-30: plan several moves around multiple anchors, ending on the
 *           hardest puzzle in World 2.
 *
 * `metadata.minMoves` records the length of the shortest solution found by
 * the BFS solver (`src/game/engine/solver.ts`) at authoring time. Tests in
 * `levels.test.ts` re-run the solver against every level and fail if a
 * level is unsolvable, already solved at the start, or its shortest
 * solution no longer matches `minMoves` (a regression signal).
 *
 * `metadata.stars` gives each level its own three-star curve (see
 * `StarThresholds`): `three` is the move count for a 3rd star (always the
 * optimal `minMoves` here - you cannot out-score the shortest path), `two`
 * the 2nd star. The slack between `minMoves` and `two` widens with tier
 * (+2 for the teaching tiers, +3 for the planning tiers, +4 for the
 * finale) so "solved but inefficiently" reliably lands on one star.
 */
export const LEVELS: ReadonlyArray<LevelDefinition> = [
  // ======================================================================
  // Tier 1 (levels 1-5): very easy - teach the basic mechanic.
  // No obstacles at all. Each level introduces one new idea about how
  // gravity works, one at a time.
  // ======================================================================
  {
    id: 'level-001',
    order: 1,
    name: 'First Drop',
    rows: 5,
    cols: 5,
    objects: [{ row: 0, col: 2 }],
    targets: [{ row: 4, col: 2 }],
    obstacles: [],
    difficulty: 'easy',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['tutorial'], notes: 'Teaches: pressing a direction drops the object all the way to the edge.' },
  },
  {
    id: 'level-002',
    order: 2,
    name: 'Slide Over',
    rows: 5,
    cols: 5,
    objects: [{ row: 2, col: 0 }],
    targets: [{ row: 2, col: 4 }],
    obstacles: [],
    difficulty: 'easy',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['tutorial'], notes: 'Teaches: gravity can point sideways (right), not just down.' },
  },
  {
    id: 'level-003',
    order: 3,
    name: 'Rise Up',
    rows: 5,
    cols: 5,
    objects: [{ row: 4, col: 2 }],
    targets: [{ row: 0, col: 2 }],
    obstacles: [],
    difficulty: 'easy',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['tutorial'], notes: "Teaches: gravity can point 'up' too - all four directions exist." },
  },
  {
    id: 'level-004',
    order: 4,
    name: 'Corner to Corner',
    rows: 5,
    cols: 5,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 4, col: 4 }],
    obstacles: [],
    difficulty: 'easy',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['tutorial'], notes: 'Teaches: combining two directions in sequence (down, then right).' },
  },
  {
    id: 'level-005',
    order: 5,
    name: 'Up and Over',
    rows: 5,
    cols: 5,
    objects: [{ row: 4, col: 4 }],
    targets: [{ row: 0, col: 0 }],
    obstacles: [],
    difficulty: 'easy',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['tutorial'], notes: 'Same idea as level 4, mirrored, using up+left - confirms the lesson generalizes.' },
  },

  // ======================================================================
  // Tier 2 (levels 6-10): introduce obstacles and positioning.
  // Every level here has exactly one movable object; the challenge is
  // reading how an obstacle changes where gravity will stop it.
  // ======================================================================
  {
    id: 'level-006',
    order: 6,
    name: 'Soft Landing',
    rows: 6,
    cols: 6,
    objects: [{ row: 0, col: 2 }],
    targets: [{ row: 3, col: 2 }],
    obstacles: [{ row: 4, col: 2 }],
    difficulty: 'easy',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['obstacles'], notes: 'Teaches: an obstacle can stop an object short of the board edge.' },
  },
  {
    id: 'level-007',
    order: 7,
    name: 'Wall Stop',
    rows: 6,
    cols: 6,
    objects: [{ row: 3, col: 0 }],
    targets: [{ row: 3, col: 4 }],
    obstacles: [{ row: 3, col: 5 }],
    difficulty: 'easy',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['obstacles'], notes: 'Same idea, sideways - the target is one cell short of the true wall.' },
  },
  {
    id: 'level-008',
    order: 8,
    name: 'Under and Across',
    rows: 6,
    cols: 6,
    objects: [{ row: 5, col: 1 }],
    targets: [{ row: 2, col: 4 }],
    obstacles: [{ row: 1, col: 1 }, { row: 2, col: 5 }],
    difficulty: 'medium',
    metadata: {
      minMoves: 2,
      stars: { two: 4, three: 2 },
      tags: ['obstacles', 'positioning'],
      notes:
        'First tier-2 level that needs two moves: rise until an obstacle stops ' +
        'you at a row, then slide across into the far obstacle. Complements ' +
        'level 9 (stop across first, then drop) rather than repeating levels ' +
        '6-7 a third time with a single-move obstacle stop.',
    },
  },
  {
    id: 'level-009',
    order: 9,
    name: 'Threading the Needle',
    rows: 6,
    cols: 6,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 5, col: 2 }],
    obstacles: [{ row: 0, col: 3 }],
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['obstacles', 'positioning'], notes: 'Positioning lesson: slide right until the wall stops you exactly above the target column, then drop.' },
  },
  {
    id: 'level-010',
    order: 10,
    name: 'Two Turns',
    rows: 6,
    cols: 6,
    objects: [{ row: 0, col: 1 }],
    targets: [{ row: 3, col: 3 }],
    obstacles: [{ row: 0, col: 4 }, { row: 4, col: 3 }],
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['obstacles', 'positioning'], notes: 'Two obstacles, two roles: one aligns the column, the other sets the final depth.' },
  },

  // ======================================================================
  // Tier 3 (levels 11-15): multiple objects and more complex sequences.
  // Objects now block, stack on, and depend on each other.
  // ======================================================================
  {
    id: 'level-011',
    order: 11,
    name: 'Two of a Kind',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 1 }, { row: 0, col: 5 }],
    targets: [{ row: 6, col: 1 }, { row: 6, col: 5 }],
    obstacles: [],
    difficulty: 'medium',
    metadata: { minMoves: 1, stars: { two: 4, three: 1 }, tags: ['multi-object'], notes: 'Teaches: one gravity change moves every object on the board at once.' },
  },
  {
    id: 'level-013',
    order: 12,
    name: 'Stack Up',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 2 }, { row: 2, col: 2 }, { row: 0, col: 5 }],
    targets: [{ row: 5, col: 2 }, { row: 6, col: 2 }, { row: 6, col: 5 }],
    obstacles: [],
    difficulty: 'medium',
    metadata: {
      minMoves: 1,
      stars: { two: 4, three: 1 },
      tags: ['multi-object'],
      notes:
        'Placed before "Trading Places" so tier 3 escalates cleanly: first the ' +
        'new idea that objects sharing a column stack on top of each other ' +
        '(still one move), then objects that must collide on purpose (two moves).',
    },
  },
  {
    id: 'level-012',
    order: 13,
    name: 'Trading Places',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 1 }, { row: 0, col: 5 }],
    targets: [{ row: 6, col: 5 }, { row: 6, col: 6 }],
    obstacles: [],
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 5, three: 2 }, tags: ['multi-object'], notes: 'The two objects end up sharing a row and must slide into each other on purpose.' },
  },
  {
    id: 'level-014',
    order: 14,
    name: 'Two Lanes',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 2 }, { row: 0, col: 4 }],
    targets: [{ row: 6, col: 2 }, { row: 6, col: 6 }],
    obstacles: [{ row: 6, col: 3 }],
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 5, three: 2 }, tags: ['multi-object', 'obstacles'] },
  },
  {
    id: 'level-015',
    order: 15,
    name: 'Three-Point Landing',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 1 }, { row: 0, col: 3 }, { row: 0, col: 5 }],
    targets: [{ row: 6, col: 1 }, { row: 3, col: 3 }, { row: 6, col: 6 }],
    obstacles: [{ row: 4, col: 3 }, { row: 3, col: 4 }, { row: 6, col: 2 }],
    difficulty: 'medium',
    metadata: {
      minMoves: 2,
      stars: { two: 5, three: 2 },
      tags: ['multi-object', 'obstacles'],
      notes:
        'Three objects, three different stopping depths. Deliberately requires a ' +
        'second move (drop, then slide right) so tier 3 ends by easing into tier ' +
        "4's multi-move planning instead of a flat single-move finish.",
    },
  },

  // ======================================================================
  // Tier 4 (levels 16-20): plan several gravity changes ahead.
  // Direct routes are deliberately blocked; the player must sequence
  // moves rather than react to just the next one.
  // ======================================================================
  {
    id: 'level-016',
    order: 16,
    name: 'The Detour',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 4 }],
    targets: [{ row: 7, col: 0 }],
    obstacles: [{ row: 3, col: 4 }, { row: 0, col: 1 }],
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['planning'], notes: 'The direct route down is blocked - drop, detour left, then drop again.' },
  },
  {
    id: 'level-017',
    order: 17,
    name: 'Make Room',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 3 }, { row: 4, col: 3 }],
    targets: [{ row: 7, col: 3 }, { row: 4, col: 7 }],
    obstacles: [{ row: 0, col: 4 }, { row: 5, col: 7 }],
    difficulty: 'hard',
    metadata: { minMoves: 2, stars: { two: 5, three: 2 }, tags: ['planning', 'multi-object'], notes: 'The lower object is in the way - it must move aside before the falling one can pass.' },
  },
  {
    id: 'level-018',
    order: 18,
    name: 'Around the Block',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 0, col: 7 }],
    obstacles: [{ row: 0, col: 3 }, { row: 0, col: 4 }, { row: 0, col: 5 }],
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['planning', 'obstacles'], notes: 'A wall blocks the direct route across the top - go down, across, and back up.' },
  },
  {
    id: 'level-019',
    order: 19,
    name: 'Triple Threat',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 1 }, { row: 0, col: 4 }, { row: 0, col: 6 }],
    targets: [{ row: 7, col: 3 }, { row: 4, col: 4 }, { row: 7, col: 7 }],
    obstacles: [{ row: 5, col: 4 }, { row: 7, col: 4 }, { row: 4, col: 5 }],
    difficulty: 'expert',
    metadata: { minMoves: 2, stars: { two: 5, three: 2 }, tags: ['planning', 'multi-object'], notes: 'Three objects with three different obstacle interactions, resolved in one carefully-chosen pair of moves.' },
  },
  {
    id: 'level-020',
    order: 20,
    name: 'The Maze',
    rows: 9,
    cols: 9,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 8, col: 8 }],
    obstacles: [{ row: 3, col: 0 }, { row: 3, col: 4 }, { row: 5, col: 8 }, { row: 5, col: 4 }],
    difficulty: 'expert',
    metadata: { minMoves: 5, stars: { two: 9, three: 5 }, tags: ['planning', 'obstacles'], notes: 'The grand finale of the first 20 levels - the longest required solution in the set.' },
  },

  // ======================================================================
  // WORLD 2 - ANCHORS
  //
  // Tier 5 (levels 21-23): teach anchored objects. One normal object, one
  // anchor. The anchor is a piece that never moves; a normal object stops
  // against it exactly like a wall.
  // ======================================================================
  {
    id: 'level-021',
    order: 21,
    name: 'Held in Place',
    rows: 6,
    cols: 6,
    objects: [{ row: 0, col: 2 }],
    targets: [{ row: 3, col: 2 }],
    obstacles: [],
    anchors: [{ row: 4, col: 2 }],
    difficulty: 'easy',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['anchors', 'tutorial'], notes: 'Teaches: an anchored object is a fixed blocker - the drop stops on top of it.' },
  },
  {
    id: 'level-022',
    order: 22,
    name: 'Lean On It',
    rows: 6,
    cols: 6,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 5, col: 3 }],
    obstacles: [],
    anchors: [{ row: 0, col: 4 }],
    difficulty: 'easy',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['anchors'], notes: 'Slide into the anchor to line up the column, then drop - the anchor is an alignment tool, like an obstacle.' },
  },
  {
    id: 'level-023',
    order: 23,
    name: 'Drop and Go',
    rows: 6,
    cols: 6,
    objects: [{ row: 0, col: 3 }],
    targets: [{ row: 3, col: 0 }],
    obstacles: [],
    anchors: [{ row: 4, col: 3 }],
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['anchors'], notes: 'Reverse of level 22: drop onto the anchor first (stopping mid-board), then slide off to the target.' },
  },

  // ======================================================================
  // Tier 6 (levels 24-26): anchors + obstacles. Two kinds of permanent
  // blocker in one puzzle - one sets the column, the other sets the depth.
  // ======================================================================
  {
    id: 'level-024',
    order: 24,
    name: 'Anchor and Wall',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 1 }],
    targets: [{ row: 4, col: 4 }],
    obstacles: [{ row: 0, col: 5 }],
    anchors: [{ row: 5, col: 4 }],
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['anchors', 'obstacles'], notes: 'Obstacle stops the slide to align column 4; the anchor stops the drop one row short of the floor.' },
  },
  {
    id: 'level-025',
    order: 25,
    name: 'The Ledge',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 4, col: 3 }],
    obstacles: [{ row: 5, col: 0 }],
    anchors: [{ row: 4, col: 4 }],
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['anchors', 'obstacles'], notes: 'Mirror of level 24: the obstacle makes a ledge to stop the drop at row 4, the anchor stops the slide at the target.' },
  },
  {
    id: 'level-026',
    order: 26,
    name: 'Two Blockers',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 6, col: 6 }],
    obstacles: [{ row: 0, col: 3 }],
    anchors: [{ row: 3, col: 0 }],
    difficulty: 'medium',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['anchors', 'obstacles', 'planning'], notes: 'Both diagonals are blocked (anchor down the left, obstacle across the top); either order works but it takes three moves to reach the far corner.' },
  },

  // ======================================================================
  // Tier 7 (levels 27-30): plan several moves around multiple anchors.
  // Direct routes are pinned shut; the anchors must be gone around.
  // ======================================================================
  {
    id: 'level-027',
    order: 27,
    name: 'The Outside Route',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 4 }],
    targets: [{ row: 7, col: 4 }],
    obstacles: [],
    anchors: [{ row: 3, col: 4 }, { row: 7, col: 5 }],
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['anchors', 'planning'], notes: 'The straight drop to the target is pinned shut by an anchor - go out to the left wall, down, and back in (the second anchor catches the return slide).' },
  },
  {
    id: 'level-028',
    order: 28,
    name: 'Pinned Corners',
    rows: 8,
    cols: 8,
    objects: [{ row: 7, col: 0 }],
    targets: [{ row: 0, col: 6 }],
    obstacles: [{ row: 0, col: 7 }],
    anchors: [{ row: 7, col: 3 }, { row: 3, col: 0 }],
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['anchors', 'obstacles', 'planning'], notes: 'One anchor blocks the slide along the floor, the other blocks the climb up the wall - the only way up is the short hop the floor anchor allows first. Obstacle stops the final slide on the target.' },
  },
  {
    id: 'level-029',
    order: 29,
    name: 'Release Forward',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }, { row: 3, col: 0 }],
    targets: [{ row: 7, col: 2 }, { row: 7, col: 7 }],
    obstacles: [],
    anchors: [{ row: 7, col: 3 }],
    difficulty: 'expert',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['anchors', 'multi-object', 'planning'], notes: 'Two objects stack in the left column, then the lower one is released rightward into the anchor while the upper one drops behind it and continues to the far corner.' },
  },
  {
    id: 'level-030',
    order: 30,
    name: 'The Gauntlet',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 7, col: 7 }],
    obstacles: [],
    anchors: [{ row: 0, col: 4 }, { row: 7, col: 4 }, { row: 3, col: 3 }, { row: 3, col: 7 }],
    difficulty: 'expert',
    metadata: { minMoves: 5, stars: { two: 9, three: 5 }, tags: ['anchors', 'planning'], notes: 'Four anchors turn the board into a staircase that has to be climbed down, across, up, across and down - the first genuinely long anchor puzzle before the World 2 expansion (levels 31-60) picks up the thread.' },
  },

  // ======================================================================
  // WORLD 2 EXPANSION (levels 31-60). Same mechanics (gravity, obstacles,
  // multiple objects, targets, anchored objects) - no new mechanic. Each
  // level isolates one idea; move count is NOT the only difficulty axis
  // (the 41-45 band drops back to short solutions on purpose - the new
  // demand there is reading several objects at once).
  //
  // Tier 8  (31-35): trivial gravity + anchor combinations.
  // Tier 9  (36-40): read how an anchor changes where a move ends.
  // Tier 10 (41-45): multiple objects meeting anchored objects.
  // Tier 11 (46-50): plan several gravity changes ahead.
  // Tier 12 (51-55): busier layouts, several anchors that each do a job.
  // Tier 13 (56-60): advanced but fair - everything so far, ending on the
  //                  longest required solution in the game (7 moves).
  // ======================================================================

  // ---- Tier 8 (31-35): trivial combinations ----------------------------
  {
    id: 'level-031',
    order: 31,
    name: 'Sidestop',
    rows: 6,
    cols: 6,
    objects: [{ row: 2, col: 0 }],
    targets: [{ row: 2, col: 3 }],
    obstacles: [],
    anchors: [{ row: 2, col: 4 }],
    difficulty: 'easy',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['anchors'], notes: 'The sideways version of "Held in Place": a slide stops one cell short of the wall against the anchored object.' },
  },
  {
    id: 'level-032',
    order: 32,
    name: 'Bump the Ceiling',
    rows: 6,
    cols: 6,
    objects: [{ row: 5, col: 2 }],
    targets: [{ row: 2, col: 2 }],
    obstacles: [],
    anchors: [{ row: 1, col: 2 }],
    difficulty: 'easy',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['anchors'], notes: 'Anchors stop upward gravity too - rise until the pinned object is in the way.' },
  },
  {
    id: 'level-033',
    order: 33,
    name: 'Different Depths',
    rows: 6,
    cols: 6,
    objects: [{ row: 0, col: 1 }, { row: 0, col: 4 }],
    targets: [{ row: 3, col: 1 }, { row: 4, col: 4 }],
    obstacles: [],
    anchors: [{ row: 4, col: 1 }, { row: 5, col: 4 }],
    difficulty: 'easy',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['anchors', 'multi-object'], notes: 'One pull, two objects: each stops at its own anchor, so they finish on different rows.' },
  },
  {
    id: 'level-034',
    order: 34,
    name: 'Not My Lane',
    rows: 6,
    cols: 6,
    objects: [{ row: 0, col: 2 }],
    targets: [{ row: 5, col: 2 }],
    obstacles: [],
    anchors: [{ row: 2, col: 1 }, { row: 2, col: 3 }],
    difficulty: 'easy',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['anchors'], notes: 'Two anchors flank the drop but sit in other columns - an anchor only blocks its own row or column, so the drop is clean.' },
  },
  {
    id: 'level-035',
    order: 35,
    name: 'Around the Elbow',
    rows: 6,
    cols: 6,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 3, col: 3 }],
    obstacles: [],
    anchors: [{ row: 4, col: 0 }, { row: 3, col: 4 }],
    difficulty: 'easy',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['anchors'], notes: 'Two anchors cooperate: one stops the drop, the next stops the slide - an L-shaped path in two moves.' },
  },

  // ---- Tier 9 (36-40): read how an anchor changes a move --------------
  {
    id: 'level-036',
    order: 36,
    name: 'Halfway Down',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 3 }],
    targets: [{ row: 3, col: 6 }],
    obstacles: [],
    anchors: [{ row: 4, col: 3 }],
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['anchors'], notes: 'The anchor gives a precise mid-column stop; from there one slide reaches the wall on the target row.' },
  },
  {
    id: 'level-037',
    order: 37,
    name: 'Wall, Then Rest',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 3 }],
    targets: [{ row: 4, col: 0 }],
    obstacles: [],
    anchors: [{ row: 5, col: 0 }],
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['anchors'], notes: 'Slide to the wall first; the anchor then catches the drop above the floor.' },
  },
  {
    id: 'level-038',
    order: 38,
    name: 'Corner Pocket',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 4 }],
    targets: [{ row: 7, col: 6 }],
    obstacles: [],
    anchors: [{ row: 7, col: 7 }],
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['anchors'], notes: 'An anchor against the far wall turns the second-to-last cell into a pocket you slide into.' },
  },
  {
    id: 'level-039',
    order: 39,
    name: 'Wrong Way Down',
    rows: 6,
    cols: 6,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 5, col: 0 }],
    obstacles: [],
    anchors: [{ row: 3, col: 0 }],
    difficulty: 'medium',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['anchors', 'planning'], notes: 'Dropping straight down is pinned shut - the target is only reachable by leaving the column and coming back along the floor.' },
  },
  {
    id: 'level-040',
    order: 40,
    name: 'The Long Way Round',
    rows: 7,
    cols: 7,
    objects: [{ row: 6, col: 0 }],
    targets: [{ row: 6, col: 5 }],
    obstacles: [],
    anchors: [{ row: 6, col: 4 }],
    difficulty: 'medium',
    metadata: { minMoves: 4, stars: { two: 7, three: 4 }, tags: ['anchors', 'planning'], notes: 'A single anchor mid-row blocks the direct slide - the object has to go up, across the top, down the far wall and back in.' },
  },

  // ---- Tier 10 (41-45): multiple objects + anchors -------------------
  {
    id: 'level-041',
    order: 41,
    name: 'Stacked Landing',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 3 }, { row: 1, col: 3 }],
    targets: [{ row: 3, col: 3 }, { row: 4, col: 3 }],
    obstacles: [],
    anchors: [{ row: 5, col: 3 }],
    difficulty: 'medium',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['anchors', 'multi-object'], notes: 'An anchor lets a two-object stack come to rest in the middle of the board instead of on the floor.' },
  },
  {
    id: 'level-042',
    order: 42,
    name: 'One Lane Blocked',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 1 }, { row: 0, col: 4 }],
    targets: [{ row: 6, col: 1 }, { row: 2, col: 4 }],
    obstacles: [],
    anchors: [{ row: 3, col: 4 }],
    difficulty: 'medium',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['anchors', 'multi-object'], notes: 'The same pull sends the two objects to very different places because only one column has an anchor in it.' },
  },
  {
    id: 'level-043',
    order: 43,
    name: 'Three at Once',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 1 }, { row: 0, col: 4 }, { row: 0, col: 6 }],
    targets: [{ row: 7, col: 1 }, { row: 3, col: 4 }, { row: 5, col: 6 }],
    obstacles: [],
    anchors: [{ row: 4, col: 4 }, { row: 6, col: 6 }],
    difficulty: 'medium',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['anchors', 'multi-object'], notes: 'Three objects, three different anchor situations, all resolved by a single drop - the challenge is reading all three at once.' },
  },
  {
    id: 'level-044',
    order: 44,
    name: 'Wedged Still',
    rows: 7,
    cols: 7,
    objects: [{ row: 3, col: 6 }, { row: 0, col: 6 }],
    targets: [{ row: 3, col: 1 }, { row: 2, col: 0 }],
    obstacles: [],
    anchors: [{ row: 3, col: 0 }, { row: 4, col: 1 }],
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['anchors', 'multi-object', 'planning'], notes: 'Slide one object into a pocket where it is trapped against the next gravity pull, so the move that places the other object leaves it alone.' },
  },
  {
    id: 'level-045',
    order: 45,
    name: 'Blocked From Behind',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 1 }, { row: 0, col: 3 }],
    targets: [{ row: 5, col: 0 }, { row: 6, col: 0 }],
    obstacles: [],
    anchors: [{ row: 6, col: 1 }],
    difficulty: 'medium',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['anchors', 'multi-object', 'planning'], notes: 'One object has to become a stop for the other; the anchor sets the vertical offset between their two targets.' },
  },

  // ---- Tier 11 (46-50): plan several moves ahead ---------------------
  {
    id: 'level-046',
    order: 46,
    name: 'Wedge and Pin',
    rows: 8,
    cols: 8,
    objects: [{ row: 5, col: 7 }, { row: 7, col: 5 }],
    targets: [{ row: 5, col: 0 }, { row: 2, col: 5 }],
    obstacles: [],
    anchors: [{ row: 4, col: 0 }, { row: 6, col: 0 }, { row: 1, col: 5 }, { row: 7, col: 4 }],
    difficulty: 'hard',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['anchors', 'multi-object', 'planning'], notes: 'Two objects placed by a single pull: one is wedged between two anchors so it holds still, the other is pinned in its column so it does not drift.' },
  },
  {
    id: 'level-047',
    order: 47,
    name: 'Two-Step Stair',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 7, col: 7 }],
    obstacles: [],
    anchors: [{ row: 3, col: 0 }, { row: 0, col: 4 }],
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['anchors', 'planning'], notes: 'One anchor caps the first drop, the other caps the first slide - a two-step staircase to the far corner.' },
  },
  {
    id: 'level-048',
    order: 48,
    name: 'Back to the Middle',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 7, col: 4 }],
    obstacles: [],
    anchors: [{ row: 3, col: 0 }, { row: 7, col: 3 }],
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['anchors', 'planning'], notes: 'The start-column anchor makes going down first the slow way; going around and letting the floor anchor catch you lands exactly on target.' },
  },
  {
    id: 'level-049',
    order: 49,
    name: 'Double Back',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 4 }],
    targets: [{ row: 0, col: 0 }],
    obstacles: [],
    anchors: [{ row: 0, col: 2 }, { row: 3, col: 0 }, { row: 3, col: 4 }],
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['anchors', 'planning'], notes: 'The target is on the start row but an anchor blocks the direct slide - drop, cross under, and rise back up into it.' },
  },
  {
    id: 'level-050',
    order: 50,
    name: 'Over the Top',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 7, col: 7 }],
    obstacles: [{ row: 0, col: 4 }],
    anchors: [{ row: 7, col: 3 }],
    difficulty: 'hard',
    metadata: { minMoves: 4, stars: { two: 7, three: 4 }, tags: ['anchors', 'obstacles', 'planning'], notes: 'An obstacle caps the top row and an anchor caps the floor; the object has to zig-zag between them in four moves.' },
  },

  // ---- Tier 12 (51-55): busier layouts, several anchors -------------
  {
    id: 'level-051',
    order: 51,
    name: 'Middle Child',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }, { row: 0, col: 3 }, { row: 2, col: 7 }],
    targets: [{ row: 7, col: 0 }, { row: 3, col: 3 }, { row: 7, col: 1 }],
    obstacles: [],
    anchors: [{ row: 4, col: 3 }, { row: 3, col: 2 }],
    difficulty: 'hard',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['anchors', 'multi-object', 'planning'], notes: 'Three objects: the middle one is wedged so the second move (needed for the third object) does not disturb it; the third object stops against the first.' },
  },
  {
    id: 'level-052',
    order: 52,
    name: 'Every Route Pinned',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 4 }],
    targets: [{ row: 7, col: 0 }],
    obstacles: [],
    anchors: [{ row: 3, col: 4 }, { row: 0, col: 2 }, { row: 7, col: 2 }],
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['anchors', 'planning'], notes: 'Three anchors close off the direct drop and both floor approaches - the only path is drop, cross, drop.' },
  },
  {
    id: 'level-053',
    order: 53,
    name: 'Wall and Pin',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 7, col: 2 }],
    obstacles: [{ row: 0, col: 4 }],
    anchors: [{ row: 7, col: 1 }],
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['anchors', 'obstacles', 'planning'], notes: 'The obstacle sets which column you fall down; the floor anchor stops the last slide dead on the target.' },
  },
  {
    id: 'level-054',
    order: 54,
    name: 'The Staircase',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 6, col: 7 }],
    obstacles: [],
    anchors: [{ row: 4, col: 0 }, { row: 3, col: 4 }, { row: 7, col: 3 }],
    difficulty: 'hard',
    metadata: { minMoves: 4, stars: { two: 7, three: 4 }, tags: ['anchors', 'planning'], notes: 'A clean four-leg serpentine - one anchor caps each leg: down, across, down, across.' },
  },
  {
    id: 'level-055',
    order: 55,
    name: 'Threading Two',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }, { row: 0, col: 1 }],
    targets: [{ row: 7, col: 6 }, { row: 7, col: 7 }],
    obstacles: [],
    anchors: [{ row: 3, col: 0 }, { row: 3, col: 1 }, { row: 4, col: 7 }],
    difficulty: 'hard',
    metadata: { minMoves: 5, stars: { two: 9, three: 5 }, tags: ['anchors', 'multi-object', 'planning'], notes: 'Two objects share a zig-zag corridor formed by paired anchors; they stay a step apart the whole way down.' },
  },

  // ---- Tier 13 (56-60): advanced but fair --------------------------
  {
    id: 'level-056',
    order: 56,
    name: 'Early Drop',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 5, col: 7 }],
    obstacles: [],
    anchors: [{ row: 0, col: 4 }, { row: 3, col: 0 }, { row: 6, col: 7 }],
    difficulty: 'expert',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['anchors', 'planning'], notes: 'An anchor on the start row forces an early drop; a far anchor stops the final fall one row above the floor.' },
  },
  {
    id: 'level-057',
    order: 57,
    name: 'Neither Edge',
    rows: 8,
    cols: 8,
    objects: [{ row: 7, col: 0 }],
    targets: [{ row: 0, col: 7 }],
    obstacles: [{ row: 7, col: 3 }],
    anchors: [{ row: 3, col: 0 }, { row: 0, col: 3 }],
    difficulty: 'expert',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['anchors', 'obstacles', 'planning'], notes: 'The bottom row is blocked by an obstacle and the top row by an anchor - the object threads the middle (rising twice) to reach the far top corner.' },
  },
  {
    id: 'level-058',
    order: 58,
    name: 'Hold and Route',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }, { row: 4, col: 7 }],
    targets: [{ row: 7, col: 3 }, { row: 7, col: 7 }],
    obstacles: [],
    anchors: [{ row: 3, col: 7 }, { row: 5, col: 7 }, { row: 7, col: 4 }],
    difficulty: 'expert',
    metadata: { minMoves: 4, stars: { two: 7, three: 4 }, tags: ['anchors', 'multi-object', 'planning'], notes: 'One object is wedged in the right-hand column while the other is walked left, down, right and down into its target.' },
  },
  {
    id: 'level-059',
    order: 59,
    name: 'The Weave',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 7 }],
    targets: [{ row: 7, col: 3 }],
    obstacles: [{ row: 0, col: 4 }],
    anchors: [{ row: 4, col: 7 }, { row: 7, col: 4 }, { row: 3, col: 3 }],
    difficulty: 'expert',
    metadata: { minMoves: 6, stars: { two: 10, three: 6 }, tags: ['anchors', 'obstacles', 'planning'], notes: 'A six-move weave: down, across, up, across, down, and one last slide onto the target between two blockers.' },
  },
  {
    id: 'level-060',
    order: 60,
    name: 'Everything Learned',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 7, col: 7 }],
    obstacles: [{ row: 0, col: 4 }, { row: 7, col: 4 }],
    anchors: [{ row: 3, col: 3 }, { row: 3, col: 7 }, { row: 4, col: 0 }],
    difficulty: 'expert',
    metadata: { minMoves: 7, stars: { two: 11, three: 7 }, tags: ['anchors', 'obstacles', 'planning'], notes: 'The grand finale of the anchor world: obstacles cap both middle edges, three anchors break every straight line, and the only route is a seven-move climb down, across, down, back, up, across and down.' },
  },

  // ======================================================================
  // WORLD 3 - PORTALS (levels 61-70, experimental).
  //
  // A portal is a pair of linked cells. An object that slides onto either
  // cell is teleported to the other and keeps sliding in the CURRENT
  // gravity direction. At most one teleport per object per gravity action
  // (no chaining); a portal whose exit is occupied acts as a wall. No
  // anchored objects here - portals are tried on their own first.
  //
  // Tier 14 (61-63): teach portals.
  // Tier 15 (64-67): gravity + portals working together.
  // Tier 16 (68-70): portal positioning that needs several moves planned.
  // ======================================================================

  // ---- Tier 14 (61-63): teach portals -------------------------------
  {
    id: 'level-061',
    order: 61,
    name: 'In One Side',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 3 }],
    targets: [{ row: 6, col: 0 }],
    obstacles: [],
    portals: [[{ row: 3, col: 3 }, { row: 3, col: 0 }]],
    difficulty: 'easy',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['portals'], notes: 'The object falls into the portal, comes out the linked cell, and keeps falling to the floor.' },
  },
  {
    id: 'level-062',
    order: 62,
    name: 'Through the Wall',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 3, col: 6 }],
    obstacles: [
      { row: 0, col: 3 }, { row: 1, col: 3 }, { row: 2, col: 3 }, { row: 3, col: 3 },
      { row: 4, col: 3 }, { row: 5, col: 3 }, { row: 6, col: 3 }, { row: 4, col: 6 },
    ],
    portals: [[{ row: 0, col: 2 }, { row: 0, col: 4 }]],
    difficulty: 'easy',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['portals', 'obstacles'], notes: 'A solid wall of obstacles blocks the way across - the portal is the only way to the far side.' },
  },
  {
    id: 'level-063',
    order: 63,
    name: 'Either End',
    rows: 7,
    cols: 7,
    objects: [{ row: 6, col: 0 }],
    targets: [{ row: 6, col: 6 }],
    obstacles: [],
    portals: [[{ row: 6, col: 4 }, { row: 0, col: 4 }]],
    difficulty: 'easy',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['portals'], notes: 'The portal sits directly in the slide path, so it cannot be passed - enter one end, come out the other, and approach the target from the top.' },
  },

  // ---- Tier 15 (64-67): gravity + portals --------------------------
  {
    id: 'level-064',
    order: 64,
    name: 'Keep Falling',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 5 }],
    targets: [{ row: 6, col: 3 }],
    obstacles: [{ row: 6, col: 4 }],
    portals: [[{ row: 3, col: 5 }, { row: 3, col: 1 }]],
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['portals', 'obstacles'], notes: 'The object emerges from the portal mid-fall and keeps going down; one slide then puts it on the target.' },
  },
  {
    id: 'level-065',
    order: 65,
    name: 'At the Mouth',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 6, col: 0 }],
    obstacles: [{ row: 6, col: 4 }, { row: 3, col: 0 }],
    portals: [[{ row: 0, col: 4 }, { row: 6, col: 3 }]],
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['portals', 'obstacles'], notes: 'The portal exit is walled, so the object comes to rest right at the portal mouth, then slides off along the floor.' },
  },
  {
    id: 'level-066',
    order: 66,
    name: 'Two Through One',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 2 }, { row: 1, col: 2 }],
    targets: [{ row: 6, col: 5 }, { row: 5, col: 5 }],
    obstacles: [],
    portals: [[{ row: 3, col: 2 }, { row: 3, col: 5 }]],
    difficulty: 'medium',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['portals', 'multi-object'], notes: 'Both objects fall through the same portal in one move; the second stacks up behind the first as they emerge.' },
  },
  {
    id: 'level-067',
    order: 67,
    name: 'Crossing Over',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 2 }, { row: 0, col: 5 }],
    targets: [{ row: 6, col: 5 }, { row: 6, col: 2 }],
    obstacles: [],
    portals: [[{ row: 3, col: 2 }, { row: 3, col: 5 }]],
    difficulty: 'medium',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['portals', 'multi-object'], notes: 'One object is in each portal column - a single drop swaps them to opposite sides of the board.' },
  },

  // ---- Tier 16 (68-70): advanced portal positioning ---------------
  {
    id: 'level-068',
    order: 68,
    name: 'The Tunnel',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 0, col: 6 }],
    obstacles: [
      { row: 0, col: 3 }, { row: 1, col: 3 }, { row: 2, col: 3 }, { row: 3, col: 3 },
      { row: 4, col: 3 }, { row: 5, col: 3 }, { row: 6, col: 3 },
    ],
    portals: [[{ row: 6, col: 2 }, { row: 6, col: 4 }]],
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['portals', 'obstacles', 'planning'], notes: 'The portal endpoints are on the bottom row on either side of a full wall - drop to the floor, slide through the portal, then climb the far wall.' },
  },
  {
    id: 'level-069',
    order: 69,
    name: 'Come Back Down',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 6, col: 0 }],
    obstacles: [{ row: 4, col: 0 }, { row: 0, col: 4 }],
    portals: [[{ row: 3, col: 3 }, { row: 6, col: 7 }]],
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['portals', 'obstacles', 'planning'], notes: 'An obstacle stops the drop exactly on the portal row; the portal throws the object to the far corner, and a slide back along the floor finishes it.' },
  },
  {
    id: 'level-070',
    order: 70,
    name: 'The Long Loop',
    rows: 6,
    cols: 6,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 0, col: 5 }],
    obstacles: [
      { row: 0, col: 3 }, { row: 1, col: 3 }, { row: 2, col: 3 }, { row: 3, col: 3 },
      { row: 4, col: 3 }, { row: 5, col: 3 }, { row: 2, col: 5 },
    ],
    portals: [[{ row: 5, col: 2 }, { row: 2, col: 4 }]],
    difficulty: 'expert',
    metadata: { minMoves: 4, stars: { two: 7, three: 4 }, tags: ['portals', 'obstacles', 'planning'], notes: 'The portal is the only gap in the wall, and its exit is blocked on one side - drop, slide through, then two moves to work back up to the target.' },
  },

  // ======================================================================
  // WORLD 3 continued (levels 71-80): deeper portal positioning.
  // Portal endpoints placed to redirect, cross-link columns, be used in
  // both directions, or bridge a wall on a longer route.
  // ======================================================================
  {
    id: 'level-071',
    order: 71,
    name: 'Twin Gateways',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 1 }, { row: 0, col: 5 }],
    targets: [{ row: 6, col: 3 }, { row: 2, col: 3 }],
    obstacles: [{ row: 3, col: 3 }],
    portals: [[{ row: 3, col: 1 }, { row: 5, col: 3 }], [{ row: 3, col: 5 }, { row: 0, col: 3 }]],
    difficulty: 'medium',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['portals', 'multi-object'], notes: 'Two portal pairs, one drop: each object falls through its own gateway and comes to rest in the middle column.' },
  },
  {
    id: 'level-072',
    order: 72,
    name: 'Long Shot',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 6, col: 6 }],
    obstacles: [],
    portals: [[{ row: 0, col: 3 }, { row: 6, col: 0 }]],
    difficulty: 'medium',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['portals'], notes: 'One slide right: into the portal near the start, out at the far floor, and along it to the corner.' },
  },
  {
    id: 'level-073',
    order: 73,
    name: 'Sidestep Fall',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 6, col: 1 }],
    obstacles: [{ row: 6, col: 0 }],
    portals: [[{ row: 2, col: 0 }, { row: 2, col: 4 }]],
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['portals', 'obstacles'], notes: 'The portal shifts the object four columns across mid-fall; an obstacle then stops the return slide one cell short.' },
  },
  {
    id: 'level-074',
    order: 74,
    name: 'Wall Crossing',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 0, col: 6 }],
    obstacles: [
      { row: 0, col: 3 }, { row: 1, col: 3 }, { row: 2, col: 3 }, { row: 3, col: 3 },
      { row: 4, col: 3 }, { row: 5, col: 3 }, { row: 6, col: 3 },
    ],
    portals: [[{ row: 0, col: 2 }, { row: 6, col: 4 }]],
    difficulty: 'hard',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['portals', 'obstacles'], notes: 'The portal endpoints sit either side of a full wall; the only crossing is through the gateway, coming out on the floor.' },
  },
  {
    id: 'level-075',
    order: 75,
    name: 'Column Swap',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 3 }],
    targets: [{ row: 6, col: 3 }],
    obstacles: [],
    portals: [[{ row: 3, col: 3 }, { row: 3, col: 0 }]],
    difficulty: 'hard',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['portals', 'planning'], notes: 'Dropping in column 3 lands you in column 0 and vice versa - so go to column 0 first, and the drop delivers you to column 3.' },
  },
  {
    id: 'level-076',
    order: 76,
    name: 'Floor Gate',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 0, col: 7 }],
    obstacles: [
      { row: 0, col: 4 }, { row: 1, col: 4 }, { row: 2, col: 4 }, { row: 3, col: 4 },
      { row: 4, col: 4 }, { row: 5, col: 4 }, { row: 6, col: 4 }, { row: 7, col: 4 },
    ],
    portals: [[{ row: 7, col: 3 }, { row: 0, col: 5 }]],
    difficulty: 'hard',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['portals', 'obstacles'], notes: 'Drop to the floor, slide into the gateway there, and emerge on the far side of the wall near the top.' },
  },
  {
    id: 'level-077',
    order: 77,
    name: 'Far Fling',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 7, col: 0 }],
    obstacles: [{ row: 4, col: 0 }, { row: 0, col: 4 }],
    portals: [[{ row: 3, col: 3 }, { row: 7, col: 7 }]],
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['portals', 'obstacles', 'planning'], notes: 'An obstacle stops the drop on the portal row; the gateway flings the object to the opposite corner, and a slide back along the floor finishes it.' },
  },
  {
    id: 'level-078',
    order: 78,
    name: 'There and Back',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 3, col: 6 }],
    obstacles: [{ row: 2, col: 6 }, { row: 6, col: 0 }],
    portals: [[{ row: 3, col: 0 }, { row: 6, col: 3 }]],
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['portals', 'obstacles', 'planning'], notes: 'The one portal pair is used in both directions - down through it, then later back through it the other way to reach the target.' },
  },
  {
    id: 'level-079',
    order: 79,
    name: 'Bounce Down',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 6, col: 5 }],
    obstacles: [{ row: 3, col: 3 }, { row: 6, col: 6 }],
    portals: [[{ row: 0, col: 3 }, { row: 3, col: 0 }]],
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['portals', 'obstacles', 'planning'], notes: 'Slide into the top portal, drop out at the left, and thread between two obstacles to the target.' },
  },
  {
    id: 'level-080',
    order: 80,
    name: 'Mid-Air Bridge',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 7, col: 7 }],
    obstacles: [{ row: 3, col: 0 }, { row: 0, col: 3 }],
    portals: [[{ row: 2, col: 2 }, { row: 5, col: 5 }]],
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['portals', 'obstacles', 'planning'], notes: 'Both direct routes are capped by obstacles; the portal is a diagonal bridge across the middle of the board.' },
  },

  // ======================================================================
  // WORLD 4 - PORTALS & ANCHORS (levels 81-100).
  //
  // 81-90 introduce the combination: an anchor catches a portal-emerged
  // object, walls a portal exit, aligns an object to the portal's row, or
  // holds one object still while another is warped.
  // 91-100 combine everything - gravity, obstacles, multiple objects,
  // anchors and portals - with difficulty from positioning, planning and
  // object interaction (not bigger boards or move limits).
  // ======================================================================

  // ---- 81-90: introduce anchors + portals ----
  {
    id: 'level-081',
    order: 81,
    name: 'Caught on Exit',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 3 }],
    targets: [{ row: 4, col: 0 }],
    obstacles: [],
    anchors: [{ row: 5, col: 0 }],
    portals: [[{ row: 3, col: 3 }, { row: 3, col: 0 }]],
    difficulty: 'medium',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['portals', 'anchors'], notes: 'The object drops through the portal and keeps falling until an anchored object stops it exactly on the target.' },
  },
  {
    id: 'level-082',
    order: 82,
    name: 'One High, One Low',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 1 }, { row: 0, col: 5 }],
    targets: [{ row: 1, col: 1 }, { row: 6, col: 1 }],
    obstacles: [],
    anchors: [{ row: 2, col: 1 }],
    portals: [[{ row: 3, col: 5 }, { row: 3, col: 1 }]],
    difficulty: 'medium',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['portals', 'anchors', 'multi-object'], notes: 'One drop: the anchor catches the first object high in its column while the portal drops the second one to the floor of the same column.' },
  },
  {
    id: 'level-083',
    order: 83,
    name: 'Land at the Ring',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 6, col: 0 }],
    obstacles: [],
    anchors: [{ row: 6, col: 4 }, { row: 3, col: 0 }],
    portals: [[{ row: 0, col: 3 }, { row: 6, col: 3 }]],
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['portals', 'anchors'], notes: 'An anchor walls the portal exit, so the object comes to rest right at the portal mouth, then slides off to the target.' },
  },
  {
    id: 'level-084',
    order: 84,
    name: 'Warp and Stop',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 6, col: 3 }],
    obstacles: [],
    anchors: [{ row: 6, col: 4 }],
    portals: [[{ row: 2, col: 0 }, { row: 6, col: 0 }]],
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['portals', 'anchors'], notes: 'The portal drops the object to the floor corner; an anchor then stops its slide dead on the target.' },
  },
  {
    id: 'level-085',
    order: 85,
    name: 'On the Right Row',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 7, col: 7 }],
    obstacles: [],
    anchors: [{ row: 4, col: 0 }],
    portals: [[{ row: 3, col: 3 }, { row: 7, col: 3 }]],
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['portals', 'anchors', 'planning'], notes: 'The anchor stops the drop on exactly the row the portal is on, so the next slide enters the gateway instead of missing it.' },
  },
  {
    id: 'level-086',
    order: 86,
    name: 'Aligned Exit',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 7, col: 6 }],
    obstacles: [],
    anchors: [{ row: 4, col: 0 }, { row: 7, col: 7 }],
    portals: [[{ row: 3, col: 3 }, { row: 7, col: 3 }]],
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['portals', 'anchors', 'planning'], notes: 'Same idea as level 85, but a second anchor catches the emerging object one cell short of the wall, right on the target.' },
  },
  {
    id: 'level-087',
    order: 87,
    name: 'Held While You Warp',
    rows: 7,
    cols: 7,
    objects: [{ row: 3, col: 6 }, { row: 0, col: 2 }],
    targets: [{ row: 3, col: 1 }, { row: 6, col: 5 }],
    obstacles: [],
    anchors: [{ row: 3, col: 0 }, { row: 4, col: 1 }, { row: 0, col: 1 }],
    portals: [[{ row: 2, col: 2 }, { row: 2, col: 5 }]],
    difficulty: 'hard',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['portals', 'anchors', 'multi-object', 'planning'], notes: 'Slide one object into a pocket where two anchors pin it, so the drop that sends the other object through the portal leaves it untouched.' },
  },
  {
    id: 'level-088',
    order: 88,
    name: 'Gate Pass',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 3, col: 6 }],
    obstacles: [{ row: 2, col: 6 }],
    anchors: [{ row: 3, col: 0 }],
    portals: [[{ row: 2, col: 3 }, { row: 5, col: 6 }]],
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['portals', 'anchors', 'obstacles', 'planning'], notes: 'The anchor blocks the drop; from the stop you reach the portal, which throws you to the far wall; an obstacle catches the climb on target.' },
  },
  {
    id: 'level-089',
    order: 89,
    name: 'Blocked Drop',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 6 }],
    targets: [{ row: 6, col: 6 }],
    obstacles: [],
    anchors: [{ row: 3, col: 6 }],
    portals: [[{ row: 3, col: 3 }, { row: 5, col: 0 }]],
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['portals', 'anchors', 'planning'], notes: 'An anchor blocks the one-move drop down the right wall, forcing a route that crosses the board and comes back through the portal.' },
  },
  {
    id: 'level-090',
    order: 90,
    name: 'Split on the Floor',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 7, col: 4 }],
    obstacles: [],
    anchors: [{ row: 3, col: 0 }, { row: 7, col: 3 }],
    portals: [[{ row: 2, col: 3 }, { row: 5, col: 7 }]],
    difficulty: 'hard',
    metadata: { minMoves: 4, stars: { two: 7, three: 4 }, tags: ['portals', 'anchors', 'planning'], notes: 'One anchor aligns you to the portal row, the gateway flings you to the far corner, and a second anchor stops the return slide on the target.' },
  },

  // ---- 91-100: advanced, everything together ----
  {
    id: 'level-091',
    order: 91,
    name: 'Corner Warp',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }, { row: 0, col: 3 }],
    targets: [{ row: 7, col: 7 }, { row: 3, col: 3 }],
    obstacles: [],
    anchors: [{ row: 4, col: 3 }, { row: 3, col: 4 }],
    portals: [[{ row: 6, col: 0 }, { row: 6, col: 6 }]],
    difficulty: 'hard',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['portals', 'anchors', 'multi-object', 'planning'], notes: 'One drop places both objects: a floor portal warps the first across the board while two anchors catch and pin the second in the middle.' },
  },
  {
    id: 'level-092',
    order: 92,
    name: 'Hold and Send',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 0 }, { row: 0, col: 3 }],
    targets: [{ row: 6, col: 6 }, { row: 3, col: 3 }],
    obstacles: [],
    anchors: [{ row: 4, col: 3 }, { row: 3, col: 4 }],
    portals: [[{ row: 5, col: 0 }, { row: 5, col: 5 }]],
    difficulty: 'hard',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['portals', 'anchors', 'multi-object', 'planning'], notes: 'The same shape as level 91 on a smaller board - the portal is one row higher, changing which floor cell the warped object reaches.' },
  },
  {
    id: 'level-093',
    order: 93,
    name: 'Aim Through',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 7, col: 7 }],
    obstacles: [{ row: 0, col: 4 }, { row: 4, col: 0 }],
    anchors: [{ row: 7, col: 3 }, { row: 3, col: 4 }],
    portals: [[{ row: 3, col: 3 }, { row: 7, col: 5 }]],
    difficulty: 'hard',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['portals', 'anchors', 'obstacles', 'planning'], notes: 'An obstacle stops the drop level with the portal, and the gateway drops you onto the floor already past the halfway line.' },
  },
  {
    id: 'level-094',
    order: 94,
    name: 'Two Anchored Rows',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 7, col: 7 }],
    obstacles: [{ row: 0, col: 4 }],
    anchors: [{ row: 4, col: 0 }, { row: 7, col: 3 }],
    portals: [[{ row: 3, col: 3 }, { row: 3, col: 6 }]],
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['portals', 'anchors', 'obstacles', 'planning'], notes: 'The anchor puts you on the portal row, the gateway skips you across, and the drop from there needs one more slide.' },
  },
  {
    id: 'level-095',
    order: 95,
    name: 'Wall and Ring',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 0, col: 7 }],
    obstacles: [
      { row: 0, col: 4 }, { row: 1, col: 4 }, { row: 2, col: 4 }, { row: 3, col: 4 },
      { row: 4, col: 4 }, { row: 5, col: 4 }, { row: 6, col: 4 }, { row: 7, col: 4 },
    ],
    anchors: [{ row: 3, col: 5 }],
    portals: [[{ row: 7, col: 3 }, { row: 6, col: 5 }]],
    difficulty: 'expert',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['portals', 'anchors', 'obstacles', 'planning'], notes: 'The portal is the wall crossing; an anchor on the far side keeps the climb from overshooting past the target column.' },
  },
  {
    id: 'level-096',
    order: 96,
    name: 'Over the Divide',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 0, col: 7 }],
    obstacles: [
      { row: 0, col: 4 }, { row: 1, col: 4 }, { row: 2, col: 4 }, { row: 3, col: 4 },
      { row: 4, col: 4 }, { row: 5, col: 4 }, { row: 6, col: 4 }, { row: 7, col: 4 },
    ],
    anchors: [{ row: 0, col: 6 }],
    portals: [[{ row: 7, col: 3 }, { row: 2, col: 5 }]],
    difficulty: 'expert',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['portals', 'anchors', 'obstacles', 'planning'], notes: 'A higher portal exit than level 95 - you emerge partway up the far side and an anchor stops the last slide on the corner target.' },
  },
  {
    id: 'level-097',
    order: 97,
    name: 'Reverse Crossing',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 7 }],
    targets: [{ row: 7, col: 0 }],
    obstacles: [
      { row: 0, col: 4 }, { row: 1, col: 4 }, { row: 2, col: 4 }, { row: 3, col: 4 },
      { row: 4, col: 4 }, { row: 5, col: 4 }, { row: 6, col: 4 }, { row: 7, col: 4 },
    ],
    anchors: [{ row: 7, col: 5 }],
    portals: [[{ row: 7, col: 3 }, { row: 3, col: 5 }]],
    difficulty: 'expert',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['portals', 'anchors', 'obstacles', 'planning'], notes: 'Start on the far side of the wall: an anchor stops the drop level with the portal exit, then the gateway carries you across to the target side.' },
  },
  {
    id: 'level-098',
    order: 98,
    name: 'Mouth on the Wall',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 0, col: 7 }],
    obstacles: [
      { row: 0, col: 4 }, { row: 1, col: 4 }, { row: 2, col: 4 }, { row: 3, col: 4 },
      { row: 4, col: 4 }, { row: 5, col: 4 }, { row: 6, col: 4 }, { row: 7, col: 4 },
    ],
    anchors: [{ row: 2, col: 6 }],
    portals: [[{ row: 7, col: 3 }, { row: 2, col: 5 }]],
    difficulty: 'expert',
    metadata: { minMoves: 4, stars: { two: 7, three: 4 }, tags: ['portals', 'anchors', 'obstacles', 'planning'], notes: 'The anchor walls the portal exit, so you come to rest at the mouth on the far side and have to climb and slide the rest of the way in.' },
  },
  {
    id: 'level-099',
    order: 99,
    name: 'Both Through, Then Split',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }, { row: 3, col: 0 }],
    targets: [{ row: 7, col: 2 }, { row: 7, col: 7 }],
    obstacles: [],
    anchors: [{ row: 7, col: 3 }],
    portals: [[{ row: 5, col: 0 }, { row: 5, col: 5 }]],
    difficulty: 'expert',
    metadata: { minMoves: 4, stars: { two: 7, three: 4 }, tags: ['portals', 'anchors', 'multi-object', 'planning'], notes: 'Both objects fall through one portal and stack on the far floor; a single anchor then splits them - one stops on it, the other slides past to the corner.' },
  },
  {
    id: 'level-100',
    order: 100,
    name: 'Everything at Once',
    rows: 8,
    cols: 8,
    objects: [{ row: 7, col: 0 }],
    targets: [{ row: 0, col: 7 }],
    obstacles: [{ row: 7, col: 3 }, { row: 3, col: 7 }],
    anchors: [{ row: 3, col: 0 }],
    portals: [[{ row: 3, col: 3 }, { row: 0, col: 5 }]],
    difficulty: 'expert',
    metadata: { minMoves: 5, stars: { two: 9, three: 5 }, tags: ['portals', 'anchors', 'obstacles', 'planning'], notes: 'The finale of World 4: an obstacle blocks the floor, an anchor blocks the wall climb, and the portal - reached only after threading past both - is used mid-route on a five-move path to the far top corner.' },
  },

  // ======================================================================
  // WORLD 5 - GRAVITY ZONES (levels 101-110, experimental).
  //
  // A gravity zone is a rectangle where gravity always pulls one fixed way,
  // whatever the player pressed. An object's pull is re-decided every step
  // from the cell it is in, so it can turn a corner on the zone boundary;
  // if the zone pushes it straight back the way it came in, it stops at the
  // edge instead of oscillating. No portals or anchors here yet.
  //
  // Tier 20 (101-103): teach - deflect, oppose, ride out.
  // Tier 21 (104-106): global gravity + zone working together.
  // Tier 22 (107-110): more advanced planning around the zone.
  // ======================================================================

  // ---- Tier 20 (101-103): teach gravity zones ----
  {
    id: 'level-101',
    order: 101,
    name: 'Turn Right',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 4, col: 6 }],
    obstacles: [],
    zone: { minRow: 4, maxRow: 6, minCol: 0, maxCol: 6, direction: 'right' },
    difficulty: 'medium',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['gravity-zone'], notes: 'Press down: the object falls, and the moment it enters the zone gravity turns it right toward the target.' },
  },
  {
    id: 'level-102',
    order: 102,
    name: 'Pushed Back',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 3 }],
    targets: [{ row: 3, col: 3 }],
    obstacles: [],
    zone: { minRow: 3, maxRow: 6, minCol: 0, maxCol: 6, direction: 'up' },
    difficulty: 'medium',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['gravity-zone'], notes: 'The zone pulls up, so a falling object cannot get past its top edge - it comes to rest right on the boundary.' },
  },
  {
    id: 'level-103',
    order: 103,
    name: 'Ride It Out',
    rows: 7,
    cols: 7,
    objects: [{ row: 3, col: 1 }],
    targets: [{ row: 6, col: 6 }],
    obstacles: [],
    zone: { minRow: 2, maxRow: 4, minCol: 0, maxCol: 3, direction: 'right' },
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['gravity-zone'], notes: 'The object starts inside the zone, so the first press carries it right whatever you chose; once it leaves the zone your press takes over.' },
  },

  // ---- Tier 21 (104-106): global gravity + zone gravity ----
  {
    id: 'level-104',
    order: 104,
    name: 'Two Ways Down',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 1 }, { row: 0, col: 5 }],
    targets: [{ row: 6, col: 1 }, { row: 6, col: 3 }],
    obstacles: [],
    zone: { minRow: 3, maxRow: 6, minCol: 4, maxCol: 6, direction: 'left' },
    difficulty: 'medium',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['gravity-zone', 'multi-object'], notes: 'One press: the object outside the zone falls straight, the one that drops into the zone is pushed left before it lands.' },
  },
  {
    id: 'level-105',
    order: 105,
    name: 'The Shelf',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 6, col: 6 }],
    obstacles: [],
    zone: { minRow: 3, maxRow: 3, minCol: 0, maxCol: 4, direction: 'right' },
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['gravity-zone'], notes: 'A one-row zone catches the fall and slides the object sideways out of it; then it keeps falling, and a second press finishes the job.' },
  },
  {
    id: 'level-106',
    order: 106,
    name: 'Trapdoor',
    rows: 7,
    cols: 7,
    objects: [{ row: 3, col: 0 }],
    targets: [{ row: 6, col: 6 }],
    obstacles: [],
    zone: { minRow: 3, maxRow: 3, minCol: 3, maxCol: 6, direction: 'down' },
    difficulty: 'hard',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['gravity-zone'], notes: 'Slide right and the zone drops you through the floor of your lane mid-slide; press right again to finish along the bottom.' },
  },

  // ---- Tier 22 (107-110): advanced planning ----
  {
    id: 'level-107',
    order: 107,
    name: 'Bounced In',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }, { row: 0, col: 7 }],
    targets: [{ row: 7, col: 3 }, { row: 7, col: 4 }],
    obstacles: [],
    zone: { minRow: 4, maxRow: 7, minCol: 0, maxCol: 3, direction: 'right' },
    difficulty: 'hard',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['gravity-zone', 'multi-object', 'planning'], notes: 'The zone deflects the first object to the far object\'s target; then one press bounces it off the zone edge onto its own target while the second object slides in behind it.' },
  },
  {
    id: 'level-108',
    order: 108,
    name: 'The Long Way',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 7, col: 0 }],
    obstacles: [],
    zone: { minRow: 3, maxRow: 3, minCol: 0, maxCol: 6, direction: 'right' },
    difficulty: 'hard',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['gravity-zone', 'planning'], notes: 'The zone carries the object all the way across and out the far side; it falls to the floor there, and one slide brings it back to the near corner.' },
  },
  {
    id: 'level-109',
    order: 109,
    name: 'Around the Current',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 3 }],
    targets: [{ row: 6, col: 3 }],
    obstacles: [{ row: 6, col: 4 }],
    zone: { minRow: 2, maxRow: 4, minCol: 2, maxCol: 4, direction: 'up' },
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['gravity-zone', 'obstacles', 'planning'], notes: 'A central up-zone makes the straight drop impossible - route out around it, down an outside column, and back along the floor.' },
  },
  {
    id: 'level-110',
    order: 110,
    name: 'Against the Grain',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 4 }],
    targets: [{ row: 7, col: 4 }],
    obstacles: [{ row: 7, col: 5 }, { row: 0, col: 2 }],
    zone: { minRow: 2, maxRow: 5, minCol: 3, maxCol: 5, direction: 'up' },
    difficulty: 'expert',
    metadata: { minMoves: 4, stars: { two: 7, three: 4 }, tags: ['gravity-zone', 'obstacles', 'planning'], notes: 'Closes the teaching band: the up-zone sits squarely on the target column, so the object has to go down, left around the zone, down the outside, and back right along the floor into the target.' },
  },

  // ======================================================================
  // WORLD 5 EXPANSION (levels 111-140). Same single-zone rule as 101-110 -
  // one rectangle, one fixed direction, re-decided per step from the cell
  // the object is in. No new mechanic. Difficulty comes from reasoning about
  // the zone, not from longer move counts: nearly every level here is
  // UNSOLVABLE if the zone is removed.
  //
  // Two zone "shapes" recur, both consequences of the per-step rule:
  //  - a SHELF: a sideways zone butted against a wall stops a drop at the
  //    zone's near row (the wall blocks the sideways push).
  //  - a BELT / CURRENT: a zone whose direction is perpendicular to the
  //    press carries an object across it and spits it out one cell past the
  //    far edge; a zone facing the press is a one-way wall (ceiling/floor).
  //
  // Tier 23 (111-120): zone mastery - one object, walls and at most a wall
  //                     of obstacles. Learn shelves, belts, ceilings and
  //                     "route around the current".
  // Tier 24 (121-130): zone + obstacles + multiple objects. One object is
  //                     usually belted to a pinned position while gravity
  //                     handles the other.
  // Tier 25 (131-140): zone + anchored objects and/or portals. An anchor is
  //                     a precise belt-stop; a portal is a gate the current
  //                     can carry an object through a solid wall. Ends on a
  //                     four-move puzzle that uses all three.
  // ======================================================================

  // ---- Tier 23 (111-120): gravity zone mastery, one object ----
  {
    id: 'level-111',
    order: 111,
    name: 'The Shelf',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 6 }],
    targets: [{ row: 3, col: 0 }],
    obstacles: [],
    zone: { minRow: 3, maxRow: 7, minCol: 0, maxCol: 3, direction: 'left' },
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['gravity-zone'], notes: 'Teaches the SHELF: slide to the left wall, drop, and the left-pushing zone stops the fall at its top row because the wall blocks the sideways push.' },
  },
  {
    id: 'level-112',
    order: 112,
    name: 'Belt to the Wall',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 3, col: 7 }],
    obstacles: [],
    zone: { minRow: 3, maxRow: 6, minCol: 4, maxCol: 7, direction: 'right' },
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['gravity-zone'], notes: 'The mirror shelf on the right wall - the object has to be brought over the top first, then dropped alongside the zone.' },
  },
  {
    id: 'level-113',
    order: 113,
    name: 'Carried Over',
    rows: 8,
    cols: 8,
    objects: [{ row: 7, col: 0 }],
    targets: [{ row: 7, col: 7 }],
    obstacles: [{ row: 1, col: 3 }, { row: 2, col: 3 }, { row: 3, col: 3 }, { row: 4, col: 3 }, { row: 5, col: 3 }, { row: 6, col: 3 }, { row: 7, col: 3 }],
    zone: { minRow: 0, maxRow: 0, minCol: 0, maxCol: 6, direction: 'right' },
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['gravity-zone', 'obstacles'], notes: 'A full-height wall blocks every row but the top - rise into the current on row 0, let it carry you across, then drop the far side.' },
  },
  {
    id: 'level-114',
    order: 114,
    name: 'The Gap in the Wall',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 7, col: 7 }],
    obstacles: [{ row: 0, col: 4 }, { row: 1, col: 4 }, { row: 2, col: 4 }, { row: 3, col: 4 }, { row: 4, col: 4 }, { row: 5, col: 4 }, { row: 7, col: 4 }],
    zone: { minRow: 6, maxRow: 6, minCol: 0, maxCol: 5, direction: 'right' },
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['gravity-zone', 'obstacles'], notes: 'The wall has a single gap on row 6, and the belt runs straight through it - drop onto the belt, ride through the gap, slide home.' },
  },
  {
    id: 'level-115',
    order: 115,
    name: 'Low Ceiling',
    rows: 8,
    cols: 8,
    objects: [{ row: 7, col: 7 }],
    targets: [{ row: 0, col: 7 }],
    obstacles: [],
    zone: { minRow: 1, maxRow: 4, minCol: 4, maxCol: 7, direction: 'down' },
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['gravity-zone', 'planning'], notes: 'A down-facing zone is a ceiling: pressing up in its columns gets you nowhere. Detour out to a clear column, rise, and come back along the top.' },
  },
  {
    id: 'level-116',
    order: 116,
    name: 'Against the Column',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 3 }],
    targets: [{ row: 7, col: 3 }],
    obstacles: [{ row: 7, col: 4 }],
    zone: { minRow: 2, maxRow: 6, minCol: 3, maxCol: 4, direction: 'up' },
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['gravity-zone', 'obstacles', 'planning'], notes: 'An up-current fills the target column - the straight drop is impossible. Go around it and let the obstacle catch the slide back in.' },
  },
  {
    id: 'level-117',
    order: 117,
    name: 'One Good Wall',
    rows: 8,
    cols: 8,
    objects: [{ row: 7, col: 0 }],
    targets: [{ row: 4, col: 7 }],
    obstacles: [],
    zone: { minRow: 4, maxRow: 7, minCol: 5, maxCol: 7, direction: 'right' },
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['gravity-zone', 'planning'], notes: 'The shelf against the right wall can only be reached from above - rise, cross the top, and drop into it.' },
  },
  {
    id: 'level-118',
    order: 118,
    name: 'Drop Through',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 4, col: 4 }],
    obstacles: [{ row: 5, col: 4 }, { row: 4, col: 5 }],
    zone: { minRow: 2, maxRow: 3, minCol: 0, maxCol: 7, direction: 'down' },
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['gravity-zone', 'obstacles', 'planning'], notes: 'A full-width down-zone drops a sideways slide through the floor of its band mid-motion; two obstacles make a pocket for the object to settle in.' },
  },
  {
    id: 'level-119',
    order: 119,
    name: 'The Long Detour',
    rows: 8,
    cols: 8,
    objects: [{ row: 7, col: 0 }],
    targets: [{ row: 0, col: 0 }],
    obstacles: [],
    zone: { minRow: 2, maxRow: 3, minCol: 0, maxCol: 5, direction: 'down' },
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['gravity-zone', 'planning'], notes: 'The ceiling covers the start column - the only way up is to cross to a clear column first, then rise, then come back.' },
  },
  {
    id: 'level-120',
    order: 120,
    name: 'Serpentine',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 4 }],
    targets: [{ row: 7, col: 4 }],
    obstacles: [{ row: 7, col: 3 }, { row: 0, col: 6 }],
    zone: { minRow: 2, maxRow: 6, minCol: 4, maxCol: 5, direction: 'up' },
    difficulty: 'hard',
    metadata: { minMoves: 4, stars: { two: 7, three: 4 }, tags: ['gravity-zone', 'obstacles', 'planning'], notes: 'Mastery finale: an up-current column plus two obstacles force a four-leg S - down, right, down again past the column, then left along the floor.' },
  },

  // ---- Tier 24 (121-130): gravity zone + obstacles + multiple objects ----
  {
    id: 'level-121',
    order: 121,
    name: 'Hold the Door',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 1 }, { row: 0, col: 2 }],
    targets: [{ row: 7, col: 0 }, { row: 3, col: 7 }],
    obstacles: [{ row: 4, col: 2 }],
    zone: { minRow: 3, maxRow: 3, minCol: 2, maxCol: 7, direction: 'right' },
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['gravity-zone', 'multi-object', 'obstacles'], notes: 'The belt carries one object to the right wall, where the current pins it. The second move places the other object without disturbing it.' },
  },
  {
    id: 'level-122',
    order: 122,
    name: 'Belt Stop',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 7 }],
    targets: [{ row: 3, col: 4 }],
    obstacles: [{ row: 3, col: 5 }, { row: 7, col: 6 }],
    zone: { minRow: 3, maxRow: 3, minCol: 0, maxCol: 6, direction: 'right' },
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['gravity-zone', 'obstacles'], notes: 'An obstacle sits in the belt - the object rides the current until it jams against it, one cell short of the wall, on the target.' },
  },
  {
    id: 'level-123',
    order: 123,
    name: 'Two Lanes, One Stream',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 2 }, { row: 0, col: 5 }],
    targets: [{ row: 4, col: 0 }, { row: 4, col: 7 }],
    obstacles: [{ row: 5, col: 0 }, { row: 5, col: 7 }],
    zone: { minRow: 4, maxRow: 4, minCol: 1, maxCol: 6, direction: 'right' },
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['gravity-zone', 'multi-object', 'obstacles'], notes: 'Both objects drop onto the same belt but exit it in different columns; obstacles then hold each on its own shelf.' },
  },
  {
    id: 'level-124',
    order: 124,
    name: 'Shelf for Two',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 6 }, { row: 0, col: 7 }],
    targets: [{ row: 2, col: 0 }, { row: 2, col: 1 }],
    obstacles: [],
    zone: { minRow: 2, maxRow: 6, minCol: 0, maxCol: 4, direction: 'left' },
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['gravity-zone', 'multi-object'], notes: 'Slide both objects into the zone column, then drop - the left-pushing current stacks them along its top row against the wall.' },
  },
  {
    id: 'level-125',
    order: 125,
    name: 'Escort to the Corner',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }, { row: 0, col: 1 }],
    targets: [{ row: 7, col: 3 }, { row: 7, col: 7 }],
    obstacles: [{ row: 7, col: 4 }],
    zone: { minRow: 3, maxRow: 3, minCol: 1, maxCol: 4, direction: 'right' },
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['gravity-zone', 'multi-object', 'obstacles'], notes: 'The belt shifts one object three columns across mid-fall so the two end up on opposite sides of an obstacle - impossible without the current.' },
  },
  {
    id: 'level-126',
    order: 126,
    name: 'Over the Wall',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 0, col: 7 }],
    obstacles: [{ row: 0, col: 4 }, { row: 1, col: 4 }, { row: 2, col: 4 }, { row: 3, col: 4 }, { row: 4, col: 4 }],
    zone: { minRow: 6, maxRow: 6, minCol: 0, maxCol: 6, direction: 'right' },
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['gravity-zone', 'obstacles'], notes: 'The wall only reaches halfway down - fall to the belt below it, ride across, and rise the far side. Two moves instead of the three the detour would take.' },
  },
  {
    id: 'level-127',
    order: 127,
    name: 'The Pocket',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 7 }],
    targets: [{ row: 5, col: 7 }],
    obstacles: [{ row: 1, col: 7 }, { row: 2, col: 7 }, { row: 3, col: 7 }, { row: 6, col: 7 }, { row: 5, col: 6 }],
    zone: { minRow: 4, maxRow: 4, minCol: 0, maxCol: 6, direction: 'right' },
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['gravity-zone', 'obstacles'], notes: 'The target pocket is walled off from above; the only way in is to ride the belt to the right wall and drop the last cell into it.' },
  },
  {
    id: 'level-128',
    order: 128,
    name: 'Shelf, Then Slide',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 5 }, { row: 0, col: 6 }],
    targets: [{ row: 2, col: 0 }, { row: 7, col: 7 }],
    obstacles: [{ row: 3, col: 6 }],
    zone: { minRow: 2, maxRow: 6, minCol: 0, maxCol: 3, direction: 'left' },
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['gravity-zone', 'multi-object', 'obstacles', 'planning'], notes: 'One object goes onto the shelf; the other is held by an obstacle mid-fall, then released down and across once the first is safe.' },
  },
  {
    id: 'level-129',
    order: 129,
    name: 'Hold the Door II',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 5 }, { row: 0, col: 6 }],
    targets: [{ row: 7, col: 7 }, { row: 4, col: 0 }],
    obstacles: [{ row: 3, col: 5 }],
    zone: { minRow: 4, maxRow: 4, minCol: 0, maxCol: 5, direction: 'left' },
    difficulty: 'hard',
    metadata: { minMoves: 4, stars: { two: 7, three: 4 }, tags: ['gravity-zone', 'multi-object', 'obstacles', 'planning'], notes: 'A four-move version: the left belt has to be fed one object at a time, with a trip to the far corner in between.' },
  },
  {
    id: 'level-130',
    order: 130,
    name: 'Escort II',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }, { row: 0, col: 5 }],
    targets: [{ row: 7, col: 0 }, { row: 3, col: 7 }],
    obstacles: [{ row: 4, col: 5 }, { row: 4, col: 0 }],
    zone: { minRow: 3, maxRow: 3, minCol: 4, maxCol: 7, direction: 'right' },
    difficulty: 'hard',
    metadata: { minMoves: 4, stars: { two: 7, three: 4 }, tags: ['gravity-zone', 'multi-object', 'obstacles', 'planning'], notes: 'Both objects need the belt, but obstacles mean they cannot use it on the same press - a four-move escort.' },
  },

  // ---- Tier 25 (131-140): gravity zone + anchored objects and/or portals ----
  {
    id: 'level-131',
    order: 131,
    name: 'Anchor in the Stream',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 1 }],
    targets: [{ row: 4, col: 4 }],
    obstacles: [],
    anchors: [{ row: 4, col: 5 }],
    zone: { minRow: 4, maxRow: 4, minCol: 0, maxCol: 6, direction: 'right' },
    difficulty: 'medium',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['gravity-zone', 'anchors'], notes: 'Teaches the combination: an anchored object in the belt is a precise stop - the current carries the object into it and no further.' },
  },
  {
    id: 'level-132',
    order: 132,
    name: 'Warp in the Stream',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 1 }],
    targets: [{ row: 7, col: 5 }],
    obstacles: [],
    portals: [[{ row: 4, col: 4 }, { row: 4, col: 5 }]],
    zone: { minRow: 4, maxRow: 4, minCol: 0, maxCol: 3, direction: 'right' },
    difficulty: 'medium',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['gravity-zone', 'portals'], notes: 'A portal endpoint sits just past the end of the belt: the current delivers the object into the gateway, and it drops out the far side.' },
  },
  {
    id: 'level-133',
    order: 133,
    name: 'Anchored Belt Stop',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 7 }],
    targets: [{ row: 4, col: 2 }],
    obstacles: [],
    anchors: [{ row: 4, col: 3 }],
    zone: { minRow: 4, maxRow: 4, minCol: 0, maxCol: 6, direction: 'right' },
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['gravity-zone', 'anchors', 'planning'], notes: 'The object starts past the anchor - it has to be brought back to the left wall first, so the belt then feeds it into the anchor from the correct side.' },
  },
  {
    id: 'level-134',
    order: 134,
    name: 'Left-Belt Anchor',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 4, col: 4 }],
    obstacles: [],
    anchors: [{ row: 4, col: 3 }],
    zone: { minRow: 4, maxRow: 4, minCol: 1, maxCol: 7, direction: 'left' },
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['gravity-zone', 'anchors', 'planning'], notes: 'Mirror of 133 with a left-pushing belt: cross to the right wall, then the current carries the object left into the anchor.' },
  },
  {
    id: 'level-135',
    order: 135,
    name: 'Warp Above the Shelf',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 7 }],
    targets: [{ row: 3, col: 0 }],
    obstacles: [{ row: 0, col: 3 }],
    portals: [[{ row: 0, col: 5 }, { row: 2, col: 0 }]],
    zone: { minRow: 3, maxRow: 7, minCol: 0, maxCol: 2, direction: 'left' },
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['gravity-zone', 'portals', 'planning'], notes: 'An obstacle blocks the slide to the shelf column; the portal is the only way to get above it, then a drop lands on the shelf.' },
  },
  {
    id: 'level-136',
    order: 136,
    name: 'Split at the Anchor',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }, { row: 0, col: 7 }],
    targets: [{ row: 4, col: 3 }, { row: 7, col: 0 }],
    obstacles: [],
    anchors: [{ row: 4, col: 4 }],
    zone: { minRow: 4, maxRow: 4, minCol: 0, maxCol: 6, direction: 'right' },
    difficulty: 'medium',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['gravity-zone', 'anchors', 'multi-object', 'planning'], notes: 'One object rides the belt into the anchor and is pinned there by the current; the other is walked to the far corner on the second move.' },
  },
  {
    id: 'level-137',
    order: 137,
    name: 'Gateway Current',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 0, col: 7 }],
    obstacles: [{ row: 0, col: 4 }, { row: 1, col: 4 }, { row: 2, col: 4 }, { row: 3, col: 4 }, { row: 4, col: 4 }, { row: 5, col: 4 }, { row: 6, col: 4 }, { row: 7, col: 4 }],
    portals: [[{ row: 5, col: 3 }, { row: 3, col: 5 }]],
    zone: { minRow: 5, maxRow: 5, minCol: 0, maxCol: 2, direction: 'right' },
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['gravity-zone', 'portals', 'obstacles', 'planning'], notes: 'A solid wall; the belt carries the object into a portal endpoint on its own side, and it emerges partway up the far side.' },
  },
  {
    id: 'level-138',
    order: 138,
    name: 'Through the Gate, Climb',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 0, col: 7 }],
    obstacles: [{ row: 0, col: 4 }, { row: 1, col: 4 }, { row: 2, col: 4 }, { row: 3, col: 4 }, { row: 4, col: 4 }, { row: 5, col: 4 }, { row: 6, col: 4 }, { row: 7, col: 4 }],
    portals: [[{ row: 2, col: 3 }, { row: 6, col: 5 }]],
    zone: { minRow: 2, maxRow: 2, minCol: 0, maxCol: 2, direction: 'right' },
    difficulty: 'hard',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['gravity-zone', 'portals', 'obstacles', 'planning'], notes: 'Same crossing, lower exit: the object drops out near the floor of the far side and has to slide and climb the rest of the way.' },
  },
  {
    id: 'level-139',
    order: 139,
    name: 'Everything at the Current',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 0, col: 7 }],
    obstacles: [{ row: 0, col: 4 }, { row: 1, col: 4 }, { row: 2, col: 4 }, { row: 3, col: 4 }, { row: 4, col: 4 }, { row: 5, col: 4 }, { row: 6, col: 4 }, { row: 7, col: 4 }, { row: 5, col: 7 }],
    anchors: [{ row: 2, col: 6 }],
    portals: [[{ row: 2, col: 3 }, { row: 6, col: 6 }]],
    zone: { minRow: 2, maxRow: 2, minCol: 0, maxCol: 2, direction: 'right' },
    difficulty: 'hard',
    metadata: { minMoves: 4, stars: { two: 7, three: 4 }, tags: ['gravity-zone', 'portals', 'anchors', 'obstacles', 'planning'], notes: 'The far side is boxed by an obstacle and an anchor, so the emerge-and-climb has to zig-zag around both in four moves.' },
  },
  {
    id: 'level-140',
    order: 140,
    name: 'The Long Current',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }, { row: 0, col: 7 }],
    targets: [{ row: 4, col: 3 }, { row: 7, col: 7 }],
    obstacles: [{ row: 4, col: 0 }],
    anchors: [{ row: 4, col: 4 }],
    portals: [[{ row: 6, col: 5 }, { row: 6, col: 0 }]],
    zone: { minRow: 4, maxRow: 4, minCol: 0, maxCol: 6, direction: 'right' },
    difficulty: 'expert',
    metadata: { minMoves: 4, stars: { two: 7, three: 4 }, tags: ['gravity-zone', 'anchors', 'portals', 'multi-object', 'planning'], notes: 'World 5 finale: one object is belted into the anchor and pinned; the other is routed through the portal and around, using the current, the anchor and the gateway in one four-move line.' },
  },

  // ======================================================================
  // World 6 - Hazards (levels 141-150). A hazard cell destroys any object
  // that slides onto it, instantly failing the puzzle (see
  // `isPuzzleFailed`) - the first mechanic in the game with a genuine fail
  // state, not just "not solved yet". 141-143 teach it in isolation: read
  // the board, find the one direction that survives. 144-147 combine it
  // with obstacles and an anchor, which now double as *safety*, not just
  // blockers - something to route behind rather than just around. 148-150
  // raise the stakes with tighter, multi-step gauntlets where more than one
  // wrong move is a dead end.
  // ======================================================================
  {
    id: 'level-141',
    order: 141,
    name: 'Mind the Gap',
    rows: 5,
    cols: 5,
    objects: [{ row: 2, col: 0 }],
    targets: [{ row: 2, col: 4 }],
    obstacles: [],
    hazards: [{ row: 4, col: 0 }],
    difficulty: 'easy',
    metadata: { minMoves: 1, stars: { two: 3, three: 1 }, tags: ['hazard', 'tutorial'], notes: 'Teaches the hazard tile: a plain sideways slide never goes near it, so it introduces the danger without punishing you yet.' },
  },
  {
    id: 'level-142',
    order: 142,
    name: 'Wrong Way Down',
    rows: 5,
    cols: 5,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 4, col: 4 }],
    obstacles: [],
    hazards: [{ row: 4, col: 0 }],
    difficulty: 'easy',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['hazard', 'tutorial'], notes: 'Pressing down first drops straight onto the hazard. Right, then down, reaches the target safely - order matters now, not just direction.' },
  },
  {
    id: 'level-143',
    order: 143,
    name: 'Wrong Way Down, Mirrored',
    rows: 5,
    cols: 5,
    objects: [{ row: 0, col: 4 }],
    targets: [{ row: 4, col: 0 }],
    obstacles: [],
    hazards: [{ row: 4, col: 4 }],
    difficulty: 'easy',
    metadata: { minMoves: 2, stars: { two: 4, three: 2 }, tags: ['hazard', 'tutorial'], notes: 'Same lesson as 142, mirrored - confirms it generalizes: whichever corner the hazard sits in, that corner is a trap.' },
  },
  {
    id: 'level-144',
    order: 144,
    name: 'Detour Around Danger',
    rows: 6,
    cols: 6,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 5, col: 5 }],
    obstacles: [{ row: 5, col: 0 }],
    hazards: [{ row: 0, col: 5 }],
    difficulty: 'medium',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['hazard', 'obstacles', 'planning'], notes: 'Sliding right first runs straight into the hazard. Down first is stopped short by the obstacle, leaving a safe route the rest of the way.' },
  },
  {
    id: 'level-145',
    order: 145,
    name: 'Detour Around Danger, Mirrored',
    rows: 6,
    cols: 6,
    objects: [{ row: 0, col: 5 }],
    targets: [{ row: 5, col: 0 }],
    obstacles: [{ row: 5, col: 5 }],
    hazards: [{ row: 0, col: 0 }],
    difficulty: 'medium',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['hazard', 'obstacles', 'planning'], notes: 'Mirror of 144 - the obstacle that looked like just an obstacle is what keeps the safe route safe.' },
  },
  {
    id: 'level-146',
    order: 146,
    name: 'Narrow Ledge',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 6, col: 6 }],
    obstacles: [{ row: 0, col: 3 }],
    hazards: [{ row: 6, col: 0 }],
    difficulty: 'medium',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['hazard', 'obstacles', 'planning'], notes: 'Down first is fatal. The obstacle caps how far right you can go before it is safe to drop.' },
  },
  {
    id: 'level-147',
    order: 147,
    name: 'Anchor and Danger',
    rows: 7,
    cols: 7,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 6, col: 6 }],
    obstacles: [],
    anchors: [{ row: 0, col: 6 }],
    hazards: [{ row: 6, col: 0 }],
    difficulty: 'medium',
    metadata: { minMoves: 3, stars: { two: 6, three: 3 }, tags: ['hazard', 'anchors', 'planning'], notes: 'Same fatal drop as 146, this time the safe stop is set by an anchor instead of an obstacle.' },
  },
  {
    id: 'level-148',
    order: 148,
    name: 'The Gauntlet',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 7, col: 7 }],
    obstacles: [{ row: 0, col: 2 }, { row: 4, col: 1 }],
    hazards: [{ row: 7, col: 0 }],
    difficulty: 'hard',
    metadata: { minMoves: 4, stars: { two: 8, three: 4 }, tags: ['hazard', 'obstacles', 'planning'], notes: 'Dropping straight down is fatal from the first move. Two obstacles turn the safe route into a genuine four-move plan.' },
  },
  {
    id: 'level-149',
    order: 149,
    name: 'Twin Threats',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 7, col: 7 }],
    obstacles: [{ row: 2, col: 0 }, { row: 1, col: 4 }],
    hazards: [{ row: 0, col: 7 }],
    difficulty: 'hard',
    metadata: { minMoves: 4, stars: { two: 8, three: 4 }, tags: ['hazard', 'obstacles', 'planning'], notes: 'This time it is the very first slide right that is fatal - the safe opening move is down, capped early by an obstacle.' },
  },
  {
    id: 'level-150',
    order: 150,
    name: 'The Final Hazard',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 7, col: 7 }],
    obstacles: [{ row: 0, col: 3 }],
    anchors: [{ row: 4, col: 2 }],
    hazards: [{ row: 7, col: 0 }],
    difficulty: 'hard',
    metadata: { minMoves: 4, stars: { two: 8, three: 4 }, tags: ['hazard', 'obstacles', 'anchors', 'planning'], notes: 'The fatal drop from level 146 returns, and this time both an obstacle and an anchor are needed to thread the safe route.' },
  },

  // ======================================================================
  // World 6 expansion (151-156): hazards fold into the gravity zone and
  // portal mechanics from Worlds 3-5. A "belt" zone that carries an object
  // to a hazard exactly one cell past its own far edge (see Step 14's SHELF/
  // BELT note) turns "ride the current" from a convenience into a trap -
  // the safe route is whichever approach never enters the belt at all, or
  // uses a portal to bypass it. Every level here still solves in the same
  // two moves the World 6 opener taught: read the board, pick the one
  // direction that survives, then finish.
  // ======================================================================
  {
    id: 'level-151',
    order: 151,
    name: 'Current of No Return',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 7, col: 7 }],
    obstacles: [],
    hazards: [{ row: 4, col: 6 }],
    zone: { minRow: 4, maxRow: 4, minCol: 0, maxCol: 5, direction: 'right' },
    difficulty: 'hard',
    metadata: { minMoves: 2, stars: { two: 5, three: 2 }, tags: ['hazard', 'gravity-zone', 'planning'], notes: 'Dropping straight down rides the belt to its far edge and one step further, into the hazard. Column 7 is outside the belt entirely - a clean drop from there.' },
  },
  {
    id: 'level-152',
    order: 152,
    name: 'Current of No Return, Mirrored',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 7 }],
    targets: [{ row: 7, col: 0 }],
    obstacles: [],
    hazards: [{ row: 4, col: 1 }],
    zone: { minRow: 4, maxRow: 4, minCol: 2, maxCol: 7, direction: 'left' },
    difficulty: 'hard',
    metadata: { minMoves: 2, stars: { two: 5, three: 2 }, tags: ['hazard', 'gravity-zone', 'planning'], notes: 'Mirror of 151 - the belt now runs left, and column 0 is the one lane it never touches.' },
  },
  {
    id: 'level-153',
    order: 153,
    name: 'Gateway to Danger',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 7, col: 7 }],
    obstacles: [],
    hazards: [{ row: 7, col: 0 }],
    portals: [[{ row: 0, col: 3 }, { row: 6, col: 3 }]],
    difficulty: 'hard',
    metadata: { minMoves: 2, stars: { two: 5, three: 2 }, tags: ['hazard', 'portals', 'planning'], notes: 'The top row hides a portal partway along it - sliding right rides it down to row 6 and out to the wall, clear of the hazard waiting at the bottom of column 0.' },
  },
  {
    id: 'level-154',
    order: 154,
    name: 'Gateway to Danger, Mirrored',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 7 }],
    targets: [{ row: 7, col: 0 }],
    obstacles: [],
    hazards: [{ row: 7, col: 7 }],
    portals: [[{ row: 0, col: 4 }, { row: 6, col: 4 }]],
    difficulty: 'hard',
    metadata: { minMoves: 2, stars: { two: 5, three: 2 }, tags: ['hazard', 'portals', 'planning'], notes: 'Mirror of 153 - the gateway sits under the top-left slide instead.' },
  },
  {
    id: 'level-155',
    order: 155,
    name: 'Everything, Carefully',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 0 }],
    targets: [{ row: 7, col: 7 }],
    obstacles: [],
    hazards: [{ row: 4, col: 7 }],
    zone: { minRow: 4, maxRow: 4, minCol: 0, maxCol: 6, direction: 'right' },
    portals: [[{ row: 0, col: 3 }, { row: 6, col: 0 }]],
    difficulty: 'expert',
    metadata: { minMoves: 2, stars: { two: 5, three: 2 }, tags: ['hazard', 'gravity-zone', 'portals', 'planning'], notes: 'World 6 finale: the same fatal belt as 151, but the safe route now goes through a portal on the way - everything the world taught, read correctly, still finishes in two moves.' },
  },
  {
    id: 'level-156',
    order: 156,
    name: 'Everything, Carefully, Mirrored',
    rows: 8,
    cols: 8,
    objects: [{ row: 0, col: 7 }],
    targets: [{ row: 7, col: 0 }],
    obstacles: [],
    hazards: [{ row: 4, col: 0 }],
    zone: { minRow: 4, maxRow: 4, minCol: 1, maxCol: 7, direction: 'left' },
    portals: [[{ row: 0, col: 4 }, { row: 6, col: 7 }]],
    difficulty: 'expert',
    metadata: { minMoves: 2, stars: { two: 5, three: 2 }, tags: ['hazard', 'gravity-zone', 'portals', 'planning'], notes: 'Mirror of 155, and the true finale - every mechanic in the game, read correctly, is still just two confident moves.' },
  },
];

/**
 * The star thresholds a level scores against. Almost always taken straight
 * from `level.metadata.stars`; the fallback only exists so a level authored
 * without explicit thresholds still scores predictably (optimal = 3 stars,
 * up to ~double = 2) instead of crashing or handing out free 3-star ratings.
 */
export function getStarThresholds(level: LevelDefinition): StarThresholds {
  if (level.metadata?.stars) return level.metadata.stars;

  const optimal = level.metadata?.minMoves ?? 1;
  return { three: optimal, two: Math.max(optimal + 2, optimal * 2) };
}

/** Looks up a level by its stable id. Returns `undefined` if not found. */
export function getLevelById(id: string): LevelDefinition | undefined {
  return LEVELS.find(level => level.id === id);
}

/** Looks up a level by its 1-based play order. Returns `undefined` if not found. */
export function getLevelByOrder(order: number): LevelDefinition | undefined {
  return LEVELS.find(level => level.order === order);
}
